fixtures:
  repositories:
    'concat':
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.2.5'
    'stdlib':
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
  symlinks:
    'portage': "#{source_dir}"
